### PR TITLE
Newlook

### PR DESCRIPTION
**Pull request by krishnatejaperannagari**
completed the new look for buildfarm waiting for review

### CODE REVIEW

**Comment by jelmer** [comment]
Thanks for the merge request. However, the comments from earlier still apply. Please re-use the existing templates from samba-web. Perhaps we can add samba-web as a submodule?

**Comment by krishnatejaperannagari** [comment]
comment in mail

**Comment by krishnatejaperannagari** [comment]
the problem is that the build farm is not of fixed size it automatically
adjusts itself to the screen size.
second thing we are placing our search box in right column and thats a
problem again.
third thing is that our pages are of radom size few big and few small so i
had to elimate few boxes that are in the right side

but i will just review code once more and see if i can combine the
buildfarm features and use the templates directly from samba web. i am
using the css from samba web so changes to samba web style will be
reflected directly in our buildfarm

On Tue, Jun 24, 2014 at 1:33 AM, Jelmer Vernooij notifications@github.com
wrote:

> Thanks for the merge request. However, the comments from earlier still
> apply. Please re-use the existing templates from samba-web. Perhaps we can
> add samba-web as a submodule?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jelmer/build-farm/pull/7#issuecomment-46894405.

## 

krishna teja perannagari

**Comment by krishnatejaperannagari** [comment]
i checked again about your idea if u can see in picture we are using the
links on left side few bxes on right side and a big box containing  links
at the bottom

the links caant be used from main site because they are different similarly
we are using ony two boxes at the right (donations and releases) they are
not available seperately to link from main site

_links in bottom box are all relative_ (/samba/what_is_samba.html). they
work only when the page is samba.org then the link becomes(
www.samba.org/samba/what_is_samba.html) they wont wrk in our site

so using existing templates from samba-web seems impractical to me.. as we
are _using samba css_ the changes will be reflected in our site

i cant underastand adding samba-web as a submodule thing?

On Tue, Jun 24, 2014 at 3:19 PM, Krishna Teja <
krishnatejaperannagari@gmail.com> wrote:

> the problem is that the build farm is not of fixed size it automatically
> adjusts itself to the screen size.
> second thing we are placing our search box in right column and thats a
> problem again.
> third thing is that our pages are of radom size few big and few small so i
> had to elimate few boxes that are in the right side
> 
> but i will just review code once more and see if i can combine the
> buildfarm features and use the templates directly from samba web. i am
> using the css from samba web so changes to samba web style will be
> reflected directly in our buildfarm
> 
> On Tue, Jun 24, 2014 at 1:33 AM, Jelmer Vernooij <notifications@github.com
> 
> > wrote:
> > 
> > Thanks for the merge request. However, the comments from earlier still
> > apply. Please re-use the existing templates from samba-web. Perhaps we can
> > add samba-web as a submodule?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jelmer/build-farm/pull/7#issuecomment-46894405.
> 
> ## 
> 
> krishna teja perannagari

## 

krishna teja perannagari

**Comment by kblin** [comment]
Hi Krishna, I'm a bit late in the party, but let's work on getting this merged. As far as I can see, Jelmer suggested to use the CSS templates from the samba-web repository. Any reason not to?

**Comment by krishnatejaperannagari** [comment]
ya i have used the css template from the samba web only see the class
buildfarmapp
https://github.com/krishnatejaperannagari/build-farm/tree/newlook/buildfarm/web
i have listed those files also. a new stylesheet is also present and that
only for some changes that might be required to position the content in
buildfarm

mr jelmer was talking about the html files we are using
https://github.com/krishnatejaperannagari/build-farm/tree/newlook/web/changes
this is not possible to use the html files from samba web in our buildfarm
because the links are all relative from the samba.org page i.e a
href="/samba/history/"> they dont work from the buildfarm site so i have to
use sepereate html files

since we are using css i think that any changes we make in samba web willl
be reflected in buildfarm and more maintenence will not be required

On Thu, Jul 3, 2014 at 5:20 PM, Kai Blin notifications@github.com wrote:

> Hi Krishna, I'm a bit late in the party, but let's work on getting this
> merged. As far as I can see, Jelmer suggested to use the CSS templates from
> the samba-web repository. Any reason not to?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jelmer/build-farm/pull/7#issuecomment-47896768.

## 

krishna teja perannagari

**Comment by kblin** [comment]
Ah, so I see. Thanks for the pointer. Another reason we can't easily use the samba-web html is that it's riddled with apache-specific SSI code. I think I'm pretty happy with this branch. Could you rebase the branch on top of the current build-farm master?

**Comment by krishnatejaperannagari** [comment]
ya i did the merge i guess now u will be able to add those changes to
https://github.com/jelmer/build-farm

On Fri, Jul 4, 2014 at 12:56 PM, Kai Blin notifications@github.com wrote:

> Ah, so I see. Thanks for the pointer. Another reason we can't easily use
> the samba-web html is that it's riddled with apache-specific SSI code. I
> think I'm pretty happy with this branch. Could you rebase the branch on top
> of the current build-farm master?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jelmer/build-farm/pull/7#issuecomment-48015656.

## 

krishna teja perannagari

**Comment by jelmer** [comment]
On Fri, Jul 04, 2014 at 12:26:16AM -0700, Kai Blin wrote:

> Ah, so I see. Thanks for the pointer. Another reason we can't easily use the samba-web html is that it's riddled with apache-specific SSI code. I think I'm pretty happy with this branch. Could you rebase the branch on top of the current build-farm master?

SSI code is fine here, we have it enabled for the build farm as well and were using it previously.

Even if we're not going to directly reference code (like CSS) from samba-web, can you please remove some of the duplication in web/ by
using SSI?

Without that, it will be painful to keep the build farm in sync wiht any changes to the main site.

Cheers,

jelmer

**Comment by krishnatejaperannagari** [comment]
i reead about ssi from http://httpd.apache.org/docs/current/howto/ssi.html and it says that to use ssl the files must be on same server so ssl might not be useful here

we use yield util.FileLoad(os.path.join(webdir, "changes/bannernav.html")) to attach the html files i dont know if the ssl work even in this case

**Comment by kblin** [comment]
Hang on, you seem to be confusing ssi and ssl (<- that's an L) here a bit. The build farm generates static HTML pages that can be served from an apache server that supports SSI. This is local to the apache server and has nothing to do with how you access these pages. It's true that you can't include remote content via SSI, but that wasn't what Jelmer suggested in any case.

**Comment by krishnatejaperannagari** [comment]
ya i was talking about server side includes only typed L by mistake.  weren't u talking about adding the content from samba web by using the server side includes code  . 

since we cant use the SSI method here may be we need to use python code or some module like urllib2 to getfiles using http

**Comment by jelmer** [comment]
On Sat, Jul 05, 2014 at 06:25:26AM -0700, krishnatejaperannagari wrote:

> ya i was talking about server side includes only typed L by mistake.  weren't u talking about adding the content from samba web by using the server side includes code  . 
> 
> since we cant use the SSI method here may be we need to use python code or some module like urllib2 to getfiles using http
> It's also possible to depend on the main Samba web repository using a
> Git submodule. I think that would reduce the maintenance overhead as
> much as possible.

Cheers,

Jelmer

**Comment by krishnatejaperannagari** [comment]
i have added changes for using ssi here i am using this repo https://github.com/krishnatejaperannagari/samba-web  where in unnecessary files are deleted, links are modified a bit and the submodule refers to this repo

modified the /web html pages also according to this layout

when u want to update the changes u need to first make changes to the repo https://github.com/krishnatejaperannagari/samba-web take care about the links expressed as href="/samba/ we need to replace them with href="http://www.samba.org//samba/

and make changes to the .gitmodules to refer to the new commit

i will test it after installing apache just see if any modifications are required because i have deleted most of the files and folders that are in original samba web

**Comment by jelmer** [comment]
On Tue, Jul 08, 2014 at 09:34:35AM -0700, krishnatejaperannagari wrote:

> i have added changes for using ssi here i am using this repo https://github.com/krishnatejaperannagari/samba-web  where in unnecessary files are deleted, links are modified a bit and the submodule refers to this repo
> Thanks.
> 
> modified the /web html pages also according to this layout
> 
> when u want to update the changes u need to first make changes to the repo https://github.com/krishnatejaperannagari/samba-web take care about the links expressed as href="/samba/ we need to replace them with href="http://www.samba.org//samba/
> I wonder if we can just create a redirect from http://buildfarm.samba.org/samba/ back to http://www.samba.org/samba/ to help with that.
> 
> and make changes to the .gitmodules to refer to the new commit
> 
> i will test it after installing apache just see if any modifications are required because i have deleted most of the files and folders that are in original samba web
> Please don't make any unnecessary changes to the samba-web repository. It
> makes it harder to review your changes and merge them back into the
> samba-web repository.

Cheers,

Jelmer

**Comment by jelmer** [comment]
On Tue, Jul 08, 2014 at 09:44:00PM +0200, Jelmer Vernooij wrote:

> On Tue, Jul 08, 2014 at 09:34:35AM -0700, krishnatejaperannagari wrote:
> 
> > i have added changes for using ssi here i am using this repo https://github.com/krishnatejaperannagari/samba-web  where in unnecessary files are deleted, links are modified a bit and the submodule refers to this repo
> > Thanks.

Can you please add changes directly under web/ rather than a separate
directory called "changes"?

"submodule" is a fairly generic term - it just describes how the
repository is embedded, not what its contents are. Perhaps rename it
to samba-web, so the path becomes web/samba-web ?

Cheers,

Jelmer

**Comment by krishnatejaperannagari** [comment]
i ran the test using apache you might need to use .cgi extension along
with .html in httpd.conf(in the server you are using) if you want these virtual headers to be parsed

replace the lines
    AddType text/html .html
    AddOutputFilter INCLUDES .html

with
    AddType text/html .html
    AddOutputFilter INCLUDES .html

but i have a doubt that since the viewbuild pages(http://build.samba.org/build.cgi/build/c33ab56a3c0b2f68c328a07861f703bc90c0bbb0) are very big will the page speed gets slowed because of apache searching for virtualheader and trying to replace them 

instead of using virtual headers and using apache we can use the code

yield util.FileLoad(os.path.join(webdir, " samba-web", "menu_think_samba_closed.html"))

or some other alterative

On Wed, Jul 9, 2014 at 1:17 AM, Jelmer Vernooij notifications@github.com
wrote:

> On Tue, Jul 08, 2014 at 09:44:00PM +0200, Jelmer Vernooij wrote:
> 
> > On Tue, Jul 08, 2014 at 09:34:35AM -0700, krishnatejaperannagari wrote:
> > 
> > > i have added changes for using ssi here i am using this repo
> > > https://github.com/krishnatejaperannagari/samba-web where in unnecessary
> > > files are deleted, links are modified a bit and the submodule refers to
> > > this repo
> > > Thanks.
> 
> Can you please add changes directly under web/ rather than a separate
> directory called "changes"?
> 
> "submodule" is a fairly generic term - it just describes how the
> repository is embedded, not what its contents are. Perhaps rename it
> to samba-web, so the path becomes web/samba-web ?
> 
> Cheers,
> 
> Jelmer
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jelmer/build-farm/pull/7#issuecomment-48390696.

## 

krishna teja perannagari

**Pull request closed without merging**
